version: '3.8'

services:
  app:
    build:
      context: ./django
      dockerfile: Dockerfile
    container_name: django_app
    command: gunicorn your_project.wsgi:application --bind 0.0.0.0:8000
    expose:
      - "8000"
    volumes:
      - static_data:/app/staticfiles
      - media_data:/app/media
    networks:
      - traefik_public
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.app.rule=Host(`cp.lojabibelo.com.br`)"
      - "traefik.http.services.app.loadbalancer.server.port=8000"

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx_static
    volumes:
      - static_data:/static
      - media_data:/media
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - traefik_public
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nginx_static.rule=Host(`static.cp.lojabibelo.com.br`)"
      - "traefik.http.routers.nginx_static.entrypoints=web"
      - "traefik.http.services.nginx_static.loadbalancer.server.port=80"
    depends_on:
      - app

volumes:
  static_data:
  media_data:

networks:
  traefik_public:
    external: true
