version: "3.7"
services:
  django:
    image: brunobh51/notiflix_v1.0.1:latest
    container_name: django_app
    command: gunicorn your_project.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_data:/app/staticfiles
      - media_volume:/app/templates/media
    expose:
      - "5000:8000"
    networks:
      - traefik_public
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.django.rule=Host(`cp.lojabibelo.com.br`)"
      - "traefik.http.services.django.loadbalancer.server.port=8000"

  nginx:
    image: nginx/nginx-ingress:latest-alpine
    container_name: nginx_static
    volumes:
      - static_data:/usr/share/nginx/html/static
      - media_volume:/usr/share/nginx/html/media
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - traefik_public
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nginx_static.rule=Host(`static.cp.lojabibelo.com.br`)"
      - "traefik.http.services.nginx_static.loadbalancer.server.port=80"

volumes:
  static_data:
  media_volume:

networks:
  traefik_public:
    external: true



