version: "3.8"

services:
  web:
    image: brunobh51/notiflix_v1.0.2:latest
    environment:
      - DEBUG=${DEBUG}
      - SECRET_KEY=${SECRET_KEY}
      - CLIENT_ID=${CLIENT_ID}
      - CLIENT_SECRET=${CLIENT_SECRET}
      - APIKEYS=${APIKEYS}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
    ports:
      - "8081:8000"
    volumes:
      - static_data:/app/staticfiles
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: '0.5'
          memory: 1024M
      labels:
        - traefik.enable=true
        - traefik.http.routers.web.rule=Host(`cp.lojabibelo.com.br`)
        - traefik.http.routers.web.entrypoints=websecure
        - traefik.http.routers.web.tls.certresolver=le
        - traefik.http.routers.web.tls=true
        - traefik.http.services.web.loadbalancer.server.port=8000
        - traefik.http.middlewares.web-compress.compress=true
        - traefik.http.routers.web.middlewares=web-compress
    networks:
      - traefik_public
      - app_network

volumes:
  static_data:
    # Pode ser necessário adicionar drivers ou opções, dependendo do uso
  media_data: # Este volume parece não estar em uso, remova ou utilize conforme necessário

networks:
  traefik_public:
    external: true
  app_network:
    external: true
