version: "3.7"
services:
  django:
    image: your-django-image
    container_name: django_app
    command: gunicorn your_project.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_data:/app/staticfiles
      - media_volume:/app/templates/media
    expose:
      - 8000
    networks:
      - traefik_public
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.django.rule=Host(`yourdomain.com`)"
      - "traefik.http.services.django.loadbalancer.server.port=8000"

  nginx:
    image: nginx:latest
    container_name: nginx_static
    volumes:
      - static_data:/usr/share/nginx/html/static
      - media_volume:/usr/share/nginx/html/media
      - ./nginx.conf:/etc/nginx/nginx.conf  # Configuração personalizada do Nginx
    networks:
      - traefik_public
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nginx_static.rule=Host(`static.yourdomain.com`)"
      - "traefik.http.services.nginx_static.loadbalancer.server.port=80"

volumes:
  static_data:
  media_volume:

networks:
  traefik_public:
    external: true
