# Generated by Django 4.2.5 on 2024-04-26 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='notificacao_email',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='notificacao_whatsapp',
            field=models.BooleanField(default=True),
        ),
    ]
