# Generated by Django 5.0.7 on 2024-09-29 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Código do Cupom')),
                ('discount_type', models.CharField(choices=[('percentage', 'Porcentagem'), ('fixed', 'Valor Fixo')], default='percentage', max_length=20, verbose_name='Tipo de Desconto')),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor do Desconto')),
                ('expiration_date', models.DateField(verbose_name='Data de Expiração')),
                ('uses', models.PositiveIntegerField(default=0, verbose_name='Usos Totais')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('expirando', 'Expirando'), ('expirado', 'Expirado')], default='ativo', max_length=20, verbose_name='Status')),
            ],
        ),
        migrations.CreateModel(
            name='CouponCriteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criteria', models.CharField(choices=[('todos', 'Todos os clientes'), ('compraram', 'Clientes que já compraram'), ('nunca_compraram', 'Clientes que nunca compraram'), ('compra_30_dias', 'Compra nos últimos 30 dias')], max_length=50, verbose_name='Critério de Seleção')),
                ('message', models.TextField(blank=True, null=True, verbose_name='Mensagem para o Cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome do Cliente')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('last_purchase_date', models.DateField(blank=True, null=True, verbose_name='Data da Última Compra')),
            ],
        ),
    ]
