# Generated by Django 5.0.4 on 2024-05-14 17:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LojaIntegrada',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('whatsapp_phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('doc', models.CharField(blank=True, max_length=14, null=True)),
                ('autorization_token', models.CharField(max_length=200)),
                ('ativa', models.BooleanField(default=True)),
                ('url', models.CharField(max_length=100)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='loja', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WhatsappIntegrado',
            fields=[
                ('instanceId', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('instanceName', models.CharField(max_length=200)),
                ('token', models.CharField(max_length=200)),
                ('status', models.CharField(blank=True, max_length=20, null=True)),
                ('loja', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp', to='app_integracao.lojaintegrada')),
            ],
        ),
    ]
