# Generated by Django 5.0.4 on 2024-04-27 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_integracao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lojaintegrada',
            name='url',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
