# Generated by Django 5.0.4 on 2024-05-11 15:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_integracao', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsappIntegrado',
            fields=[
                ('instanceId', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('instanceName', models.CharField(max_length=200)),
                ('token', models.CharField(max_length=200)),
                ('status', models.CharField(blank=True, max_length=20, null=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
