# Generated by Django 5.0.4 on 2024-05-18 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_integracao', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lojaintegrada',
            name='doc',
            field=models.CharField(blank=True, default='', max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='whatsappintegrado',
            name='token',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
