# Generated by Django 5.0.4 on 2024-05-18 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_integracao', '0002_alter_lojaintegrada_doc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lojaintegrada',
            name='webhook_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
