# Generated by Django 5.0.4 on 2024-05-20 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_integracao', '0004_lojaintegrada_events_lojaintegrada_webhook_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappintegrado',
            name='qr_code_image',
            field=models.ImageField(blank=True, null=True, upload_to='whatsapp_qrcodes/'),
        ),
    ]
