# Generated by Django 5.0.4 on 2024-05-21 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_integracao', '0005_whatsappintegrado_qr_code_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whatsappintegrado',
            name='qr_code_image',
            field=models.TextField(blank=True, null=True),
        ),
    ]
