# Generated by Django 5.0.4 on 2024-05-24 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_integracao', '0006_alter_whatsappintegrado_qr_code_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappintegrado',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
