# Generated by Django 5.0.4 on 2024-05-24 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_integracao', '0008_alter_whatsappintegrado_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whatsappintegrado',
            name='name',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Identificação WhatsApp'),
        ),
    ]
