# Generated by Django 5.0.7 on 2024-09-22 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_integracao', '0010_alter_whatsappintegrado_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='whatsappintegrado',
            old_name='name',
            new_name='numero',
        ),
    ]
