# Generated by Django 5.0.4 on 2024-05-01 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255, verbose_name='E-mail')),
                ('telefone', models.CharField(max_length=20, verbose_name='Telefone')),
                ('estado', models.CharField(max_length=100, verbose_name='Estado')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_venda', models.CharField(max_length=10, verbose_name='ID Venda')),
                ('data_pedido', models.DateField(verbose_name='Data')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('status_pagamento', models.CharField(max_length=100, verbose_name='Status Pagamento')),
                ('status_envio', models.CharField(max_length=100, verbose_name='Status Envio')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_pedido.cliente')),
            ],
        ),
    ]
