# Generated by Django 5.0.4 on 2024-05-05 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_integracao', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_name', models.CharField(blank=True, max_length=255)),
                ('contact_email', models.EmailField(blank=True, max_length=255, verbose_name='E-mail')),
                ('contact_phone', models.CharField(blank=True, max_length=20, verbose_name='Telefone')),
                ('contact_identification', models.CharField(blank=True, max_length=100, verbose_name='CPF/CNPJ')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_venda', models.CharField(blank=True, max_length=10, null=True, verbose_name='ID Venda')),
                ('id_pedido', models.BigIntegerField(blank=True, verbose_name='Número do Pedido')),
                ('data_pedido', models.DateTimeField(verbose_name='Data do Pedido')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('status_pagamento', models.CharField(max_length=100, verbose_name='Status Pagamento')),
                ('status_envio', models.CharField(default='Processando', max_length=100, verbose_name='Status Envio')),
                ('data_pagamento', models.DateField(blank=True, null=True, verbose_name='Data Pagamento')),
                ('data_embalado', models.DateField(blank=True, null=True, verbose_name='Data Embalado')),
                ('data_enviado', models.DateTimeField(blank=True, null=True, verbose_name='Data Enviado')),
                ('data_cancelado', models.DateField(blank=True, null=True, verbose_name='Data Cancelado')),
                ('data_reembolsado', models.DateField(blank=True, null=True, verbose_name='Data Reembolsado')),
                ('codigo_rastreio', models.CharField(blank=True, max_length=100, verbose_name='Código de Rastreio')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_pedido.cliente')),
                ('loja', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_integracao.lojaintegrada')),
            ],
        ),
    ]
