# Generated by Django 5.0.4 on 2024-05-19 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_integracao', '0004_lojaintegrada_events_lojaintegrada_webhook_status'),
        ('app_pedido', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='loja',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='app_integracao.lojaintegrada'),
        ),
    ]
