# Generated by Django 5.0.4 on 2024-05-01 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_pedido', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='email',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='telefone',
        ),
        migrations.AddField(
            model_name='cliente',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=255, verbose_name='E-mail'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='contact_identification',
            field=models.CharField(blank=True, max_length=100, verbose_name='cpf/cnpjyS'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='contact_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='cliente',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='data_pedido',
            field=models.DateField(blank=True, verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='id_venda',
            field=models.CharField(blank=True, max_length=10, verbose_name='ID Venda'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='status_envio',
            field=models.CharField(blank=True, max_length=100, verbose_name='Status Envio'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='status_pagamento',
            field=models.CharField(blank=True, max_length=100, verbose_name='Status Pagamento'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, verbose_name='Valor'),
        ),
    ]
