# Generated by Django 5.0.4 on 2024-05-03 03:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_integracao', '0001_initial'),
        ('app_pedido', '0002_remove_cliente_email_remove_cliente_estado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='loja',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_integracao.lojaintegrada'),
        ),
    ]
