# Generated by Django 5.0.4 on 2024-06-09 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_pedido', '0002_alter_pedido_loja'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='ultimo_status_notificado',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Último Status Notificado'),
        ),
    ]
