# Generated by Django 5.0.4 on 2024-06-09 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_pedido', '0003_pedido_ultimo_status_notificado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='id_venda',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='ID Venda'),
        ),
    ]
