# Generated by Django 5.0.4 on 2024-05-04 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_pedido', '0003_pedido_loja'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='data_cancelado',
            field=models.DateField(blank=True, null=True, verbose_name='Data Cancelado'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='data_embalado',
            field=models.DateField(blank=True, null=True, verbose_name='Data Embalado'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='data_enviado',
            field=models.DateField(blank=True, null=True, verbose_name='Data Enviado'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='data_pagamento',
            field=models.DateField(blank=True, null=True, verbose_name='Data Pagamento'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='data_reembolsado',
            field=models.DateField(blank=True, null=True, verbose_name='Data Reembolsado'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='contact_identification',
            field=models.CharField(blank=True, max_length=100, verbose_name='cpf/cnpj'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='data_pedido',
            field=models.DateField(verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='status_envio',
            field=models.CharField(max_length=100, verbose_name='Status Envio'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='status_pagamento',
            field=models.CharField(max_length=100, verbose_name='Status Pagamento'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor'),
        ),
    ]
