# Generated by Django 5.0.4 on 2024-05-04 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_pedido', '0004_pedido_data_cancelado_pedido_data_embalado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='codigo_rastreio',
            field=models.CharField(blank=True, max_length=100, verbose_name='Código de Rastreio'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='contact_identification',
            field=models.CharField(blank=True, max_length=100, verbose_name='CPF/CNPJ'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='data_enviado',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data Enviado'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='data_pedido',
            field=models.DateTimeField(verbose_name='Data do Pedido'),
        ),
    ]
