# Generated by Django 5.0.7 on 2024-11-03 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_pedido', '0005_pedido_token_pedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='accepts_marketing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cliente',
            name='billing_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='last_order_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='total_spent',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='pedido',
            name='discount_coupon_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='shipping_cost_customer',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='pedido',
            name='shipping_cost_owner',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='pedido',
            name='shipping_option_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='shipping_tracking_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='id_pedido',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Número do Pedido'),
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billing_address', models.CharField(blank=True, max_length=255, null=True)),
                ('billing_number', models.CharField(blank=True, max_length=10, null=True)),
                ('billing_floor', models.CharField(blank=True, max_length=10, null=True)),
                ('billing_locality', models.CharField(blank=True, max_length=100, null=True)),
                ('billing_zipcode', models.CharField(blank=True, max_length=10, null=True)),
                ('billing_city', models.CharField(blank=True, max_length=100, null=True)),
                ('billing_province', models.CharField(blank=True, max_length=100, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enderecos', to='app_pedido.cliente')),
            ],
        ),
    ]
