# Generated by Django 5.0.4 on 2024-05-30 11:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MensagemPadrao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_pedido', models.CharField(max_length=50)),
                ('mensagem_padrao', models.TextField()),
                ('ativado', models.BooleanField(default=True)),
                ('editado', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='MensagemPersonalizada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_pedido', models.CharField(max_length=50)),
                ('mensagem_personalizada', models.TextField()),
                ('ativado', models.BooleanField(default=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mensagens_personalizadas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
