# Generated by Django 5.0.4 on 2024-05-28 19:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_integracao', '0010_alter_whatsappintegrado_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='MensagemPersonalizada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_pedido', models.CharField(max_length=50)),
                ('mensagem', models.TextField()),
                ('loja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens_personalizadas', to='app_integracao.lojaintegrada')),
            ],
        ),
    ]
