# Generated by Django 5.0.4 on 2024-05-30 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_mensagem', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensagempadrao',
            name='tipo_pedido',
            field=models.CharField(choices=[('pedido_pago', 'Pedido Pago'), ('pedido_embalado', 'Pedido Embalado'), ('pedido_enviado', 'Pedido Enviado'), ('pedido_cancelado', 'Pedido Cancelado')], max_length=50),
        ),
        migrations.AlterField(
            model_name='mensagempersonalizada',
            name='tipo_pedido',
            field=models.CharField(choices=[('pedido_pago', 'Pedido Pago'), ('pedido_embalado', 'Pedido Embalado'), ('pedido_enviado', 'Pedido Enviado'), ('pedido_cancelado', 'Pedido Cancelado')], max_length=50),
        ),
    ]
