# Generated by Django 5.0.4 on 2024-05-29 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_mensagem', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensagempersonalizada',
            name='ativado',
            field=models.BooleanField(default=True),
        ),
    ]
