# Generated by Django 5.0.4 on 2024-06-01 01:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_mensagem', '0002_alter_mensagempadrao_tipo_pedido_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mensagempadrao',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mensagem_padrao', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mensagempadrao',
            name='tipo_pedido',
            field=models.CharField(choices=[('Pedido Pago', 'Pedido Pago'), ('Pedido Embalado', 'Pedido Embalado'), ('Pedido Enviado', 'Pedido Enviado'), ('Pedido Cancelado', 'Pedido Cancelado')], max_length=50),
        ),
        migrations.AlterField(
            model_name='mensagempersonalizada',
            name='tipo_pedido',
            field=models.CharField(choices=[('Pedido Pago', 'Pedido Pago'), ('Pedido Embalado', 'Pedido Embalado'), ('Pedido Enviado', 'Pedido Enviado'), ('Pedido Cancelado', 'Pedido Cancelado')], max_length=50),
        ),
    ]
