# Generated by Django 5.0.4 on 2024-06-01 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_mensagem', '0005_alter_mensagempadrao_tipo_pedido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensagempadrao',
            name='ativado',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
